export const Testimonials = [
  {
    id: 1,
    rating: 5,
    title: "Sunt qui esse pariatur duis deserunt mollit",
    text: "Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. ",
    name: "Cody Fisher",
    role: "Medical Assistant",
  },
  {
    id: 2,
    rating: 5,
    title: "At lectus urna duis convallis tellus",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui accumsan sit amet nulla facilisi morbi. In nibh mauris cursus mattis. At lectus urna duis convallis convallis tellus. Enim blandit volutpat maecenas volutpat.",
    role: "Nursing Assistant",
  },
  {
    id: 3,
    rating: 5,
    title: "Elit aute irure tempor cupidatat incididunt",
    text: "Aliqua id fugiat nostrud irure ex duis ea quis id quis ad et. Sunt qui esse pariatur duis deserunt mollit dolore cillum minim tempor enim. Elit aute irure tempor cupidatat incididunt sint deserunt ut voluptate aute id deserunt nisi.",
    name: "Guy Hawkins",
    role: "President of Sales",
  },
  {
    id: 4,
    rating: 5,
    title: "Donec et fringilla neque",
    text: "Aliqua id fugiat nostrud irure ex duis ea quis id quis ad et. Sunt qui esse pariatur duis deserunt mollit dolore cillum minim tempor enim. Elit aute irure tempor cupidatat incididunt sint deserunt ut voluptate aute id deserunt nisi.",
    name: "Darlene Robertson",
    role: "Dog Trainer",
  },
  {
    id: 5,
    rating: 5,
    title: "Etiam accumsan porta neque eros",
    text: "Etiam accumsan porta neque in viverra. Proin eleifend, eros in tristique hendrerit, nisi purus cursus sapien, id ultrices nunc tellus a ipsum. Donec et fringilla neque. Aenean consequat purus quis lectus maximus fermentum.",
    name: "Dianne Russell",
    role: "Medical Assistant",
  },
  {
    id: 6,
    rating: 5,
    title: "Etiam accumsan porta neque eros",
    text: "Nulla Lorem mollit cupidatat irure. Laborum magna nulla duis ullamco cillum dolor. Voluptate exercitation incididunt aliquip deserunt reprehenderit elit laborum. ",
    name: "Dianne Russell",
    role: "Medical Assistant",
  },
];
